# Generated by Django 4.2.7 on 2025-06-26 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('email', 'Email Scam'), ('sms', 'SMS Scam'), ('phone', 'Phone Call Scam'), ('website', 'Website Scam'), ('social', 'Social Media Scam'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='ScamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_detections', models.IntegerField(default=0)),
                ('scam_detections', models.IntegerField(default=0)),
                ('legitimate_detections', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Scam Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DetectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_scam', models.BooleanField()),
                ('confidence_score', models.FloatField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_feedback', models.CharField(choices=[('not_set', 'Not Set'), ('correct', 'Correct'), ('incorrect', 'Incorrect')], default='not_set', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Detection History',
                'ordering': ['-detected_at'],
            },
        ),
    ]
